apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: nmxi4a89q-dotnet-basic
  janus-idp.io/tekton: nmxi4a89q-dotnet-basic
  backstage.io/kubernetes-id: nmxi4a89q-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: nmxi4a89q-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
